### ISSUE TITLE
Document foundational technologies required for operation

### ISSUE THREAD

**Issue by jdcasey** [konflux-ci/architecture#160]
This system is built on top of OpenShift and several other technologies. It would be very helpful to a newbie if there was a list of required reading in order to understand how the pieces fit together. Just links to the docs for the relevant technologies would be enough, and park it on https://redhat-appstudio.github.io/architecture/architecture/index.html

**Comment by ralphbean** [comment]
I think some things have been added to that doc now that (while not explicitly recommending some reading) do help with this. Notably, the link to docs on the [kube controller](https://kubernetes.io/docs/concepts/architecture/controller/) concept and links to tekton documentation.

Does that help?

If we _were_ to add a section like this, I think I would only recommend reading up on that controller doc and something on an introduction to tekton.
