### ISSUE TITLE
Have a proper list of all the components needed/used

### ISSUE THREAD

**Issue by cmoulliard** [konflux-ci/architecture#55]
## TODO

It is until now really hard to figure out what is the final list of all the stonesoup components as the [book](https://redhat-appstudio.github.io/book/book/index.html)
list the following: 

- GitOps Service
- Pipeline Service
- Build Service
- Workspace and Terminal Service
- Service Provider Integration
- Hybrid Application Service
- Enterprise Contract
- Java Rebuilds Service
- Release Service
- Integration Service

**NOTE**: That should be great to have an anchor link within the https://redhat-appstudio.github.io/book/book/index.html to access the different chapters

vs another list under the [infra-deployment](https://github.com/redhat-appstudio/infra-deployments/tree/main/components) project

- application-api
- authentication
- build-service
- build-templates
- cluster-registration
- dev-sso
- dora-metrics
- enterprise-contract
- gitops-repo-pruner
- gitops
- hac-pact-broker
- has
- integration
- internal-services
- jvm-build-service
- monitoring
- pipeline-service
- quality-dashboard
- release
- shared-resources
- spi-vault
- spi
- tekton-ci

**Comment by cmoulliard** [comment]
Can we assert that the following list of the components (= folders) https://github.com/redhat-appstudio/infra-deployments/tree/main/components represents what it is needed to install on an ocp4 cluster to use `Stonesoup` ? 

Can we assert also that the following list of CRDs is equivalent to the previous list of components ?
```
CRD: applicationsets.argoproj.io
---------------------------------------------
NAME                                                                            NAMESPACE
application-api                                                                 openshift-gitops
build-service                                                                   openshift-gitops
build-templates                                                                 openshift-gitops
cluster-registration                                                            openshift-gitops
dev-sso                                                                         openshift-gitops
dora-metrics                                                                    openshift-gitops
enterprise-contract                                                             openshift-gitops
gitops                                                                          openshift-gitops
has                                                                             openshift-gitops
integration                                                                     openshift-gitops
internal-services                                                               openshift-gitops
jvm-build-service                                                               openshift-gitops
pipeline-service                                                                openshift-gitops
release                                                                         openshift-gitops
shared-resources                                                                openshift-gitops
spi                                                                             openshift-gitops
spi-vault                                                                       openshift-gitops
```

As it seems that some components are missing when we issue the command to get the `application.argoproj.io` CRDs (vs what we within as folder within the infra-deployment github repo), how can we know exactly which components are part of stonesoup, have been released and deployed ?

@ralphbean @jduimovich @Michkov

**Comment by ralphbean** [comment]
I agree this is confusing.

Rather than expand the architecture document to talk more about some of those components in infra-deployments, I'm thinking we should do some reorganization of that components dir. For example, `tekton-ci` and `dev-sso` could go under an `auxilliary` directory or something, to indicate that they're not really first-class components of the system.
